# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PLtest' do

end

target 'PLtestTests' do

end

target 'PLtestUITests' do

end

pod 'PLCameraStreamingKit'
